project:
  type: website
  output-dir: docs


website:
  title: "Yogi Ramsuratkumar Satsangs"
  navbar:
    logo: "/ysk.png"
    right:
      - about.qmd
      - icon: twitter
        href: https://twitter.com
      - icon: youtube
        href: https://www.youtube.com/@yogiramsuratkumarashram1918

    
  search:
    location: navbar
    type: overlay
    copy-button: true



format:
  html:
    theme: minty
    css: styles.css



