project:
  type: website
  output-dir: docs


website:
  title: "Yogi Ramsuratkumar Satsangs"
  navbar:
    logo: "/yrsk.png"
    right:
      - about.qmd
     
      - icon: youtube
        href: https://www.youtube.com/@yogiramsuratkumarashram1918

    
  search:
    location: navbar
    type: overlay
    copy-button: true



format:
  html:
    theme: minty
    css: styles.css



