---
title: 21 -  Bhagwan asked why people were reading Ramayana and Bhagavata?
author: Sivarama Krishna Iyer
date: "04/01/2020"
categories: [Conversations, Sannidhi street]
---
There was a devotee named Sivarama Krishna Iyer. He was from Thapovanam. He and his wife Lakshmi amma would come to see Bhagwan. One day they ahd both come and Lakshmi amma had brought food for Bhagwan. After taking food in a conversation Bhagwan asked her "Amma would you like to ask anything from this beggar"? She said that she did not know to ask anything, that her husband was reading Ramayana and Mahabharatha. He knew something to ask but she did not know anything to ask. Then Bhagwan asked why people were reading Ramayana and Bhagavata and answered himself that reading the leelas of Rama and Krishna gives happiness. Then turning to Sivaram Krishna Iyer he said to both that even now if he could remember the leelas of any present day Avatar Purushas, ie., living Avatar Purushas, he would get the same ananda, the same Brahmanadam.  Then he said that he could make a lump of clay a Maha Meru and make a Maha Meru into a small lump of clay. Such is the power which he calls His Father which he admitted he possesses. He indirectly said that he was an Avatara Purusha meaning he is an incarnation of God. Generally he used to say that he was a lazy crazy beggar but occassionally to some devotees he had revealed his true state of being.
 
Please follow the [link](https://youtu.be/IXu0X6W-VgY?si=89RpSj-LfHBwUN2X) for the satsang in youtube.
