---
title: 387 - Agaram Jayaraman's mistake and Bhagavan's leela on correcting it
author: Agaram Jayaraman
date: "07/20/2021"
categories: [Sannidhi street]
---
Ma narrated the leela from Sannadhi street when Agaram Jayaraman was at the Ashram during a solar eclipse when Bhagwan gave Ganga water to Agaram Jayaraman, another person and consumed some Himself in very precise different amounts. He later gave Agaram Jayaraman, his mother two apples and gave a third apple to Jayaraman to hand over to two people who gave the Ganga water some time ago, Bhagwan knew they would be at Thapovanam. Jayaraman marked this apple with his nail to identify, Bhagwan realized this took the apple and asked to cut into three equal pieces for Himself, Jayaraman and the other person. Later He handed another apple to Jayaraman to hand over to the two people. By this story Ma narates the importance and precision with which Bhagwan carried out his Darbar.
 
Please follow the [link](https://www.youtube.com/watch?v=7bS_6u2i0HQ) for the satsang in youtube.
