---
title: 20 - Alwar was not allowed inside to meet Bhagwan and this broke his pride
author: Alwar from Neiveli
date: "04/01/2020"
categories: [Sannidhi street]
---
Alwar was a long time devotee of Bhagwan. Bhagwan had given him some liberties. He would allow Alwar to take photographs of Bhagwan. Many times Bhagwan would also permit him to spend the night with him. So Alwar took it that he was very close to Bhagwan. Once he was coming from Chennai and he thought on the way he would go to Thiruvannamalai, have Bhagwan's darshan and then go to Neiveli. But then Bhagwan wanted people to come straight to him and go back straight.  As things were thus, Alwar came at 3'O clock in the afternoon and waited for Bhagwan. He waited and waited and Bhagwan came at 10.30 at night. Alwar rushed to him but Bhagwan sternly refused to see him and simply bolted the door. This was not expected and so Alwar was so heart broken. He wept himself out for an hour there itself booked a room, wept the whole night and next day at 4 in the morning went to see Bhagwan. He was afraid Bhagwan might not see him at all. He was absolutely humbled. But then at about 5'O Clock he suddenly heard the heavy beats of Siva Thandavam. He looked up and was dumbstruck to see Bhagwan performing an Ananda Shiva Thandavam. The Cosmic dance was so divine Alwar would not even blink his eye. This blessing continued for 45 minutes. Alwar was simply flabbergasted. Bhagwan then signals him to come and immediately takes him in and offers to spend the a whole day with him. Imagine the Abundance of Grace he received.
 
Please follow the [link](https://youtu.be/W1dwBO3RHj8?si=b-7SCA0kc3-flKt2) for the satsang in youtube.
