---
title: 64 - Angry Bhairagi and Bhagavan appearing as Kalabhairavar and Maha Vishnu
author: Appan Iyengar, Bhairaghi, Srinivasan
date: "06/01/2020"
categories: [Sannidhi street]
---
When the Bairagi was about to leave, one Srinivasan from Tapovanam, who ran a tea stall there entered the house. Bhagwan pointed to him and told the Bairagi, this man is suffering from paralysis and he could use the medicine you got from the Himalayas (Bhagwan knew he had some). The Bairagi got angry that Bhagwan was asking him to do this as he is about to leave but still he gave some to Srinivasan and not just that he blessed him that he would be cured and would have a baby boy next year. To this Bhagwan started laughing, this angered the Bairagi further and said you don't know my power and gave a piece of the medicine to Bhagwan and Appan, Bhagwan gestured Appan to consume it and consumed some Himself. This further angered the Bairagi and he faced east direction sat down and started praying to Kala Bhairava. Bhagwan's face changed now and he called out "Sai Baba, Sai Baba" Bhagwan's friend (the dog) entered pushing the heavy door of Sannadhi street. and sat under Bhagwan, Appan saw the darshan of Kala Bhairava. The Bairagi saw Sai Baba and thought oh, Kala Bhairava and later saw Bhagwan was unaffected. He thought this has not affectted Him and started praying to Hanuman. Bhagwan asked Sai Baba to go and took now the roop of Maha Vishnu, Appan got this darshan and when the Bairagi saw this he fell at the feet of Bhagwan. Bhagwan blessed him, and asked where he was going. Bairagi replied that he was going to Tirupati and Bhagwan introduced Appan as the TT and said he would help him.
 
Please follow the [link](https://youtu.be/DCtF54brF14?si=VGB2JSjakftGRgeF) for the satsang in youtube.
