---
title: 128 - Bhagwan says His father was never wrong and would never be partial to any one..
author: Mataji Devaki Ma
date: "02/02/2020"
categories: [Conversations]
---
Bhagwan said great saints performed miracles, greater saints ridiculed those performing miracles and laughed at them and the greatest saints performed miracles and laughed at them.
Bhagwan said that His father was never wrong and would never be partial to any one..
If Bhagwan would tell His Father that He didn't come to His help like He did for other devotees, Father would bring a weighing scale and prove that He was not at all partial.
Bhagwan would tell Devaki Maa that His Father would always give Him and every one what they needed and not what they wanted.
In fact, He even taught Devaki Maa to accept anything that people told or did as Father's wish and enjoy everything as the play of the Divine and not get tensed for anything. This teaching is for all of us.
 
Please follow the [link](https://youtu.be/BwWxdXcxlBU?si=KGgVhfIVlIc2xqGH) for the satsang in youtube.
