---
title: 127 - Bhagwan says "We are the puppets in the the hands of the supreme power"
author: Mataji Devaki Ma
date: "08/01/2020"
categories: [Sannidhi street]
---
Seated in the verandah of Sannidhi Street House, Yogiji declared that He was not the physical body. He said that He was present inside all of us within our hearts and will help us to come out of maya, if we were to believe this .
Devaki Ma says Bhagwan is the supreme power, which controls all the mechanisms of our life. This power has come in the form of our Bhagwan to tell us the purpose of life.
He said He was doing his work silently. His work was hidden.Bhagwan said He was born as a beggar, lived as a beggar and will be gone as beggar, difficult to comprehend.
Bhagwan would declare, "My Father alone exists, Father alone is, nothing else, no one else".
We are the puppets in the the hands of the supreme power. It is this power that activates everything in this entire cosmos.
Bhagwan would say, "Nothing belongs to me.. everything is Father's. This house belongs to Father.
Selfishness is ego. People come to the ashram to surrender ego. But here also, they expect attention, which is ego. If we don't leave the ego, then God inside us would go to sleep. Every thought of guru would bring grace."
 
Please follow the [link](https://youtu.be/iL6Y5fyZkJM?si=574qnr9tkqclcul_) for the satsang in youtube.
