---
title: 28 - Bhagwan strongly refuted him saying Pandian had been coming for Car Darshan exactly 37 times.  
author: Pandian from Madurai 
date: "04/01/2020"
categories: [Conversations, Ashram]
---
One Pandian from Madurai used to come on Pournami days to Thiruvannamalai for girivalam. He would then come promptly at the Ashram Gate where Bhagwan after giving darshan outside Pradhan Mandir would go to the car at exactly 7 O'clock. Here all people would stand by the road side and Bhagwan would give Car Darshan. Bhagwan would see everybody there, raise his hands and bless them. This Pandian also used to stand there in the line and get darshan. This happened many times and one day seeing that people were asking Bhagwan for a personal darshan, he too wanted to see Bhagwan. They would write their names and Bhagwan would call them. So he too wrote his name and waited. Two pournamis went by and it was only the third time he was called by Bhagwan. Bhagwan asked his name, enquired about his business and then just asked if he had seen Bhagwan before now. Pandian was taken aback. He replied that he had been coming for over 4 or 5 years and had been having Car Darshan of Bhagwan. At this point Bhagwan strongly refuted him saying Pandian had been coming for Car Darshan exactly 37 times.  Pandian felt it must have been many more times than that. He had been marking the days he had been to Thiruvannamalai and going home when he counted, it was exactly 37 times. In fact Pandian would humorously say that the moment anyone goes to see Bhagwan, Bhagwan would open an account for them. 
 
Please follow the [link](https://youtu.be/mOSK_SlQ12Y?si=ibjAnuZzQ-9B-wCp) for the satsang in youtube.
