---
title: 130 - Bhagwan talks about Seva to Guru and Guru is the Triveni Sangam
author: Mataji Devaki Ma
date: "09/01/2020"
categories: [Conversations]
---
Bhagwan said, Guru was verily Lord Brahma, Vishnu and Shiva, as also the Parabrahman, ie., the ultimate truth, which meant that Bhagwan was Himself the Trinity and therefore all those people were very blessed to have received the holy water sprinkled by His own Hands.
He said the place where a seer of God / Jnani is, that place is as holy as the Triveni Sangam and whenever people gather around Him, it would be as if they were taking a holy dip at the Triveni Sangam.
Seva to mankind is seva to God. Seva to God is also seva to mankind.
Seva to Sadhus and Mahatmas is the Supreme Seva.
Once Devaki Maa was taken by Bhagwan to an Amla tree and He said, "when we water the plant it reaches each and every part of the plant. Similarly when we serve a Mahatama who is in communion with the supreme, we will be serving the entire humanity."
 
Please follow the [link](https://youtu.be/uRIMy79UvbE?si=XekfyfeAL04tsSzp) for the satsang in youtube.
