---
title: 23 - Bhagwan scolds Shri.Durairaj's driver of stealing and tells him to buy lottery ticket and blesses him
author: V T Durairaj IAS
date: "04/01/2020"
categories: [Sannidhi street]
---
Sri Durairaj, I.A.S. is a devotee of Bhagwan. Once he came all the way in his car to see Bhagwan and also brought his driver to take Bhagwan's blessings. This driver was a North Indian and he was stealing money from Durairaj everyday. Bhagwan who knew this scolded him angrily in Hindi saying he was cheating on his master who was such a well wisher. The driver who realised nothing can escape Bhagwan begged his forgiveness. He said he had many commitments and so was forced to steal. Then Bhagwan said that all his financial commitments would be solved and not to resort to such papa karmas.  Bhagwan then blessed the driver and asked him to buy a lottery ticket. The driver did as Bhagwan had instructed, purchased a lottery ticket and this fetched him a prize amount of ten thousand rupees. All his debts were cleared. He felt so relieved and he served his master. Seeing how Bhagwan had forgiven him Sri Durairaj also forgave him. 
 
Please follow the [link](https://youtu.be/-3nRBGjzYro?si=nqHBSsayFj6U-wjO) for the satsang in youtube.
