---
title: 125 - Bhagwan says don't let your mind be empty. Fill all empty time with Naama, prayer and Puja, then no repulsive thoughts would come
author: Lady teacher
date: "25/01/2020"
categories: [Conversations, Sannidhi street]
---
A lady teacher visited Bhagwan along with her family from Coimbatore. Yogiji asked the lady if she was still having disturbing thoughts. She said yes..and mentioned about repulsive thoughts coming again and again..to which Bhagwan said don't let your mind be empty ..fill all empty time with Naama, prayer and Puja, then no repulsive thoughts would come. Then, He blessed her.
The lady said with sorrow that she wanted to chant Bhagwan's Naama and do work for Yogiji, but as she was caught up with her family and profession, she couldn't do it.
Bhagwan told her that wherever one may be and whatever one may be doing, all that was entirely His work only, including this lady's activities of serving  her husband and taking care of her daughter.
Yogiji also told the lady that whatever one may be doing or wherever one may be, one must have God realisation as the goal of life.
Bhagwan mentioned how Mr Morarji Desai, when told by someone that he had his life goal fulfilled after becoming PM, said, 'No, God realisation is the only goal of my life'
 
Please follow the [link](https://youtu.be/hicqh7wta1E?si=Vhr-uBW-aPJdNQt0) for the satsang in youtube.
