---
title: 110 - Bhagwan tells the story of 2 brothers who lent money from the other and the fights between them
author: Two brothers
date: "07/01/2020"
categories: [Conversation, Sannidhi street]
---
Two brothers had bought a bail petition to Bhagwan for his blessings. After they leave Bhagwan tells the story of Mr A gave a loan of 15 rupees to his brother Mr B. they were both pious but somehow Mr B did not return the money even after long time. Furthermore Mr A asks for money to be returned from Mr B infront of friends,which resulted in open fight with assaults. Mr B dies that night, at which point Mr A came to Bhagwan smugly saying that his brother had been  punished by God. Bhagwan however retorts that despite your pious nature you asked for a sum of mere 15 rupees from your brother, fought with him openly and now that he has died you will be put in jail. The police will connect the two events you too will suffer. True to that MR A was put behind bars. Bail was also denied as murder was suspected. Bhagwan says" Where there is Faith there is No Fate. But you have to remember Bhagwan constantly. Be ever vigilant and alert, even a minutes lapse in remembering Bhagwan's name will result in Fate breaking havoc. In moments of weakness the mind will go after wordly things and along with that Fate will also enter, negative forces are kept away as long as you are chanting the name. Bhagwan qoutes " In Ramayan Kaikeyi loves Rama was remembering Sri Rama all the time. But the lamenting by Manthra leads to a moment of lapse and we all know what happened after that" 
 
Please follow the [link](https://youtu.be/gqzaBjdnUfk?si=fXgx0qPKxKvhoDEd) for the satsang in youtube.
