---
title: 130 - Bhagwan says we must stay focused on our Guru Seva and not get distracted by criticism or humiliation from others
author: Mataji Devaki Ma
date: "09/01/2020"
categories: [Conversations]
---
Devaki Maa recalls Bhagwan saying, "when we do Guru Seva, we might be faced with criticism or humiliation from others. These are to be taken as Guru's mark of appreciation and love for the seva done to him and not in any other way.
We must stay focused on our Guru Seva and not get distracted by these happenings."
Bhagwan gives the example of Hanuman who faced lot of troubles and torture during his trip to Lanka in search of Maa Sita. But Hanuman ignored all these things and remained focused on Rama's work, while chanting Rama's name.
Likewise, we must also keep our minds focused on Guru Seva and be like Hanuman and not allow our minds to behave like monkey always jumping from one thought to another.
 
Please follow the [link](https://youtu.be/uRIMy79UvbE?si=XekfyfeAL04tsSzp) for the satsang in youtube.
