---
title: 27 - Bhagwan then smiled and said that it was not the butter milk that they thought was the remedy. By now they knew it was His grace acting through it
author: Ganesh anna, Ilayaraja
date: "04/01/2020"
categories: [Conversations]
---
Once Ganesh anna came to see Bhagwan. He was feeling a bit tired. Bhagwan asked him what was wrong. He said he had low BP. Bhagwan then asked him to have a glass of butter milk everyday and he would be alright. One other day a VIP friend of Ganesh anna came alongwith him to see Bhagwan. He was a VIP (Ilayaraja )from the film industry. He had high BP and thought Bhagwan might suggest something for this also. So when they came this person gestured Ganesh anna to ask Bhagwan for a remedy for his high BP. He could not bring himself to ask Bhagwan and so he gestured to Ganesh anna to ask. When Ganesh anna asked Bhagwan, Bhagwan said "Oh! ask him to take butter milk. He will be alright". Ganesh anna thought what Bhagwan did not hear probably and repeated his request, this time a little more loudly. Pat came the reply from Bhagwan  "Oh! ask him to take butter milk. He will be alright". This VIP thought Ganesh anna needed to be louder as he was suggesting the same butter milk for both low and high BP. But by now Ganesh anna knew that Bhagwan was playing a leela. Still a bit reluctantly he asked Bhagwan again in a much louder voice. Bhagwan too raised his voice and said  "Oh! ask him to take butter milk. He will be alright". Bhagwan then smiled and said that it was not the butter milk that they thought was the remedy.  By now they knew it was His grace acting through it. They shouldn't have done like this.  
 
Please follow the [link](https://youtu.be/Uy6y2Ma_xxI?si=i4aFOFOKI-bvRGvJ) for the satsang in youtube.
