---
title: 24 - Bhagwan gave lots of incense sticks to Smt. Manorama Devi and Mathaji Ram Ranjani Devi also wanted lots of incense sticks
author: Bhagwan's poorvashram relatives
date: "04/01/2020"
categories: [Sannidhi street]
---
Once Bhagwan's poorvashram relatives had come to have his darshan. His brother in law's wife, Smt. Manorama Devi for whom Bhagwan had great love and respect also had come.  Before they left Bhagwan had gathered all the packets of incense sticks from Sannadhi street house, packed them up and gave it to her. Smt. Manorama Devi went around telling everybody with pride that Swamy had sent all these for her and it would last her for a year.  Keeping this in mind when Mataji Ram Ranjani Devi came, she was also hoping to get lots of packets of incense sticks. But since nothing was coming, she sent her daughter, Bina to ask her father. Bhagwan flared but then started a leela of searching the whole place for incense sticks. They found just two sticks not even two packets which Bhagwan gave to Bina to be given to her mother. Naturally both were upset. But then being Mataji Ram Ranjani Devi realised that she should not have imitated the other woman. Had she asked for something which she needed, Bhagwan would have given and given with blessings too. This incident is a lesson for us too that we should not and need not ape anyone. Bhagwan is like a doctor who gives us what we need, not what we want. Our requirements are unique and Bhagwan is taking care of this. This assurance is there and we need to have no complaints. And that was what Bhagwan used make all sing his favorite song "Kurai Ondrum illai".
 
Please follow the [link](https://youtu.be/6O9nJOtEcQc?si=D659hIasSyGZ7OM5) for the satsang in youtube.
