---
title: 64 - Bhairagi who lost his kamandalam and Bhagavan offering money to buy a kamandalam for Bairaghi
author: Appan Iyengar, Bhairaghi
date: "06/01/2020"
categories: [Sannidhi street]
---
Appan Iyengar had visited Bhagwan in 1978 and Bhagwan suddenly got up and welcomed a Bairagi into Sannadhi street house and in front of him behaved like a Bhakta. The Bairgai on the other hand behaved like a master and informed Bhagwan that someone had stolen his Kamandalam (bowl to eat food). Bhagwan took out 10 Rs. and handed it to the Bairagi, who got angry. Bhagwan asked Appan if one could buy kamandalam with 10 Rs, to which Appan said "Yes, one can get a mud pot" but the Bairagi was still mad, so Bhagwan took out 20 Rs and same thing repeated with Appan saying one could get an Aluminum pot. This repeated until Bhagwan gave the Bairagi 60 Rs, which satisfied him. After this the Bairagi performed a pooja for this Guru, through whose grace he received this money. He performed it with a Mango and offered a piece to the Lord, one piece to Bhagwan and one to Appan. Bhagwan gestured Appan to consume the fruit and had one Himself.
 
Please follow the [link](https://youtu.be/DCtF54brF14?si=VGB2JSjakftGRgeF) for the satsang in youtube.
