---
title: 22 - Do you know the Sun up there in the sky, does it build hospitals orphanages or schools, does it have to talk to people to solve their problems but because of its shine the entire world and all its activities take place. A Yogi is like that Sun"
author: Few propagandists of Christian missionaries
date: "04/01/2020"
categories: [Conversations, Sannidhi street]
---
Once some Christian missionaries came to Bhagwan. They saw him dirty, not taking bath, wearing dirty clothes and on top of all these also smoking. How could such a dirty beggar be a Mahatma. Comparing Bhagwan to the likes of them, they even voiced it to Bhagwan saying he doesn't do anything like building hospitals, orphanages or schools etc. where as they were doing so much for the people. Bhagwan looked at Perumal Raju and replied. He did not even look at the missionaries. He said "Perumal Raju, do you know the Sun up there in the sky? Soes it build hospitals orphanages or schools, Does it have to talk to people to solve their problems but because of its shine the entire world and all its activities take place. A Yogi is like that Sun". No sooner had Bhagwan declared this, the missionaries looked at his radiant face, the power and understood the truth of the statement. They prostrated before him seeking his forgiveness. Bhagwan blessed them and then they left.
 
Please follow the [link](https://youtu.be/67fZcOv0o34?si=duWsks5tLIYHZkrl) for the satsang in youtube.
