---
title: 78 - Ganesh anna and Bhagavan's leela with butter milk
author: Sri.Ganesh Anna  & Sri.Illaiyaraja
date: "06/01/2020"
categories: [Sannidhi street]
---
Once Ganesh Anna from Ramanasramam along with Sri Illaiyaraja had come. Few days before this Sri Ganesh Anna had come to see Bhagwan for his Low BP problem for which Bhagwan had asked him to take cup of butter milk daily. Sri Ilaiyaraja had high BP and wanted Bhagwan to say what to take. Bhagwan asked to take butter milk. Sri Illaiyaraj not sure if Bhagwan heard properly, since same butter milk is being told for both low and high BP, asked Sri Ganesh Anna to repeat the problem to Bhagwan. Even after saying twice by Ganesh Anna, Bhagwan repeated to take butter milk. Then Bhagwan realised and said it is niether there in sweet balls or butter milk, it is the Sankalpa, the word and touch from them it gets cured. There has been so many devotees who seek Bhagwans blessing during the sickness. For some Bhagwan says to take certain food and it gets cured and for some they are asked to go to Doctor and Blesses them. Curious to know why this, Ma Devaki asked this to Bhagwan, for which Bhagwan said some come here with full faithfulness on Bhagwan and some on Doctor. Either way Both are being Blessed.
 
Please follow the [link](https://youtu.be/38aR2SosAT0?si=Zvt1ySE9UVCEEn3D) for the satsang in youtube.
