---
title: 44 - How a youth from Madras became rich with his blessings?
author: Youth
date: "22/01/2020"
categories: [Conversations, Sannidhi street]
---
Youth from Madras visited Yogiji and said to bless him with richness…as he wanted to be very rich and popular. He laughed a lot and said why did u come to me? What makes you think that i can help you. My friends asked me to come to you. Yogi asked -  "do you know any work?" the boy said no. Then Yogi asked " How many hours per day can u work?". He said 18 hrs a day. Swami seemed satisfied. He said i leave you and you will be successful. The boy was hesitant. He said what kind of work should i choose? Yogiji asked him what he wanted to do during the childhood . To which he said he wanted to have a very big shop.Yogiji blessed him and asked him to work in a shop even as an errand boy and work very hard. After some time the same person visited Yogiji with his wife and was looking very happy and rich. Said that he honestly worked in a department shop and the owner of the shop was very happy with his work and married his daughter to him and also made him his partner and all that he received with the blessings of Yogiji.
 
Please follow the [link](https://youtu.be/lQzX6U1bUmM?si=3Tw73M6T0OGjmHcR) for the satsang in youtube.
