---
title: 78 - How Bhagavan saved his Sannadhi street house neighbour?
author: Sri Lakshman Chettiar
date: "06/01/2020"
categories: [Sannidhi street]
---
Sri Lakshmana Chettiar had narrated some of hie memories/experiences with Bhagwan. One such was about the Sannadhi Street house. Long back the house adjancent to Bhagwan and this was 1 single house and later seem to have got bifurcated. Bhagwan was occupying and there was neighbour staying in next house. The well at back side was also shared half between both houses. One day there was thud sound and water splashing out from the well with some sound of someone shouting. Bhagwan, though knew about what had happened, got up and called Perumal who takes care. Called him to come quickly and with a ladder. This was slowly dropped down and the man who had falled and struggling tightly got hold of this ladder and slowly came up and got out. All this within few minutes had happened. Bhagwan with his presence and resources around immediately put everything to save this man from the next door. Bhagwan was practical without wasting any time.
 
Please follow the [link](https://youtu.be/38aR2SosAT0?si=Zvt1ySE9UVCEEn3D) for the satsang in youtube.
