---
title: 62 - Incident where Bhagavan asked to bring 4 chapathis and explained how everything about him was connected to cosmos.
author: Radhakrishnan, Shri Ramchandra Upadhyay, Ganeshan 
date: "06/01/2020"
categories: [Sannidhi street]
---
Ma narates the story where the weight of Bhagwan's work was shown by Bhagwan Himself. Shri Radhakrishnan and another devotee had spent the entire day with Bhagwan without eating. So when Ganeshan entered the Sannadhi Street House, Bhagwan asked him to get 4 packets of chapathi from one hotel and gave clear instructions not to bring Sambhar or Chutney. Ganeshan bought the packets along with sambhar and chutney probably upon insistence from the hotel staff. Bhagwan got really angry that his calculations had gone wrong now and asked it to be returned with a word that His account with the hotel had now closed. When Shri Ramachandra Upadhyay the hotel proprietor and devotee of Bhagwan came to know of this incidence he got very upset and visited Bhagwan, who then explained to him that everything about Bhagwan is connected with the cosmos and nothing can be changed with what He requests. Bhagwan blessed Shri Ramchandra Upadhyay
 
Please follow the [link](https://youtu.be/NU0xZWvT6hU?si=182v8FAPSplIfJcE) for the satsang in youtube.
