---
title: 15 - Jayalakshmi's scary dreams and how Bhagavan helped her to get rid of them. 
author: Jayalakshmi & Appan Iyengar
date: "04/01/2020"
categories: [Sannidhi street]
---
Jayaji was psychic and the premonitions which she got in dream, got real within days. Appanji used to mock at her and ask her  not to go to sleep. Bhagavan asked them to move to Village Achamthavirthan near Madurai. There in dream she saw dark disembodied figure in dreams very frequently. She developed tumour after that. Even when it was operated ,she felt very weak. The couple had come to bhagavan's darshan and HE asked Jayaji to walk up and down. She saw the same dark figure outside the darshan hall. She told Bhagavan about that and Bhagavan could see that. Bhagavan asked Appanji to tell that figure to go away. Twice he went out to see that there was no one. Bhagavan assured Jaya that the dark one has gone for good. This incident proves how he could move away the God of death. 
 
Please follow the [link](https://youtu.be/SGwhMQ4_xzE?si=uO7UQd5QVfPBTc4h) for the satsang in youtube.
