---
title: 63 - John Pierre's Nama chanting and how he was calm on hearing about his brother's death who had commited suicide due to psychosis.
author: John Pierre
date: "06/01/2020"
categories: [Sannidhi street]
---
Ma narates the tale of John Pierre, a devotee who was initiated to the name of Bhagwan Yogi Ramsuratkumar by Lee Lozowick. But John did not believe in Nama chanting and didn't pursue it. One day 6 years later, he got a call in the Bathroom and something in him pursuaded him to take the call and he was informed that his brother who suffered from a psychosis was found in a pool of blood. He suddenly started chanting the Nama automatically and then he noticed how he was able to calmly recieve the news and even his mother who was 86 years old responded calmly to it, even when they found out the brother had died of suicide. John was able to calmly recite the death prayer to him and even his sister who was busy with work on the day of funeral, miracles happened and she was able to join her family at the funeral. All because John started chanting the Nama and Bhagwan guided him through the process avoiding obstacles
 
Please follow the [link](https://youtu.be/FXkjtAarfI8?si=sOrzcD2gqKIaw6xn) for the satsang in youtube.
