---
title: 49 - K.V. Vishwanathan's second daughter's marriage and Bhagavan performing a miracle very similar to Bharathwaja maharishi in Ramayana. 
author: K.V. Vishwanathan
date: "05/01/2020"
categories: [Sannidhi street, Appearance in other forms]
---
Though Bhagavan did not materialise things, appear in different forms often times, he did not perform these miracles quite often, he did perform them in rare moments. A District Development officer, K. V. Vishwanathan was transferred to Thiruvannamalai. He had wanted to go to Madurai by way of transfer, however he was transferred to Thiruvannamalai. The first day he came to Thiruvannamalai, he went to Arunachaleswara temple and he ran into our Bhagavan. He started visit Bhagavan regularly. He has written many articles in the ashram magazine on his experiences. He casually asked Bhagavan if he could bring food for him and Bhagavan agreed with a condition that only the family members should cook the food. Also he said that a family member should bring the food. He happily agreed and he brought chapathi and sabji in the morning and rice gruel in the evening. He had gone through many miracles in the one year. He was transferred again. He visited Bhagavan and sought his blessings for his second daughter's marriage. Bhagavan blessed him and also quoted an incident from Ramayana. Bharathwaja maharishi was staying in the outskirts of Ayodhya. When Bharatha was on his way to the forest to get back Rama, he visited the ashram and Bharathwaja Maharishi asked them to stay in the ashram. The ashram was a simple kutir and Bharatha wondered how his army , queens and minister would be taken care of. By the strength of his penance, Bharathwaja maharishi provided accomodation to the ministers according to their ranks and peovided all the food for Bharatha's royal ministry. Bhagavan mentioned that his daughter's marriage would be taken care of like that. He also asked his friedn who had come along with K. V. Vishwanathan to come and report after the marriage. The marriage took place in a hostel with three floors. Vishwanathan was there on the first floor doing the vedic rituals, while the guests were invited in the ground floor. His friend saw Vishwanathan in the ground floor attending to the guests in the ground floor. He was wondering how he could be present in the gorund floor while he was attending to the vedic rituals. However when he went up to the first floor, Vishwanathan told his friend how he regretted not being in the ground floor inviting guests. The friend was shocked and he told Vishwanathan that he was very much present in the ground floor receiving the guests. Now Vishwanathan knew it was Bhagavan who had come and performed this leela as he had promised. His friend went and reported the whole incident to Bhagavan and Bhagavan attributed to his Father. Bhagavan also blessed one scheme of Vishanathan and assured that his district would be number one and Vishwanathan's scheme was a grand success and true to Bhagavan's words, it ranked number one.
 
Please follow the [link](https://youtu.be/zSJGuq6QBhs?si=8clLqVKbB3BzmJg9) for the satsang in youtube.
