---
title: 8 - Ma Devaki on mother's day. A beggar woman's prayers for her son's wedding despite being chased away by all of her sons. 
author: A beggar devotee
date: "04/01/2020"
categories: [Sannidhi street]
---
One beggar woman from Salem had come to Bhagavan and to bless for his last son's marriage. She mentioned that she is begging because the daughter in laws of other sons chased her away. Bhagavan enquired about her son's age and she replied it's 36. HE asked her to a light mud lamp before any deity near her abode for exactly 36 days. She told that she can beg still more and get oil, mud lamp and wick and it's easy to light lamp. Bhagavan wanted to give her some money for her to travel to Salem but she refused. She can beg on Thiruvannamalai streets for travel charges and she is very much happy for the boon and money is not required. Bhagavan was very much moved by the mother's selfless compassionate love for his son.
 
Please follow the [link](https://youtu.be/exY29yiY8ks?si=TBw0-jiBNaGkA5Av) for the satsang in youtube.
