---
title: 111 - Ma had to come back to the house in 7 min from temple and the Baby holds on the Bhagwan's thumb
author: Story on Vinayak Chathurthi day
date: "07/01/2020"
categories: [Sannidhi street , Ma & Bhagwan]
---
Ma Devaki went to have Darshan of Bhagwan at Sannidhi Street, on morning of Ganesh Chathurthi. Ma Devaki had asked a  friend to come to Bhagwan. She had an eight month baby was travelling from Chennai as she was in great difficulty. Ma Devaki sought Bhagwans permission to bring her friend from temple. It was fast approaching 12 pm at which point Bhagwan would go inside the house. Ma Devaki suddenly said "Bhagwan Should I go I will be back in 7 min". Bhagwan suddenly says "Jai Rama if Devaki doesn't return in 7 min we will put her bag outside." This meant Bhagwan would not give Darshan. Ma Devaki runs to temple much to surprise of everyone on street only to find her friend is not there , She runs back mindful of 7mins and reaches house at exactly 7th minute. Bhagwan doesn't say anything but after sometime Bhagwan drops a Modak in Ma Devaki hand. Ma Devaki had wished for this earlier. Another half an hour later he asks her to go to temple as he said her friend is there now. She comes and cries infront of Bhagwan, laments that her husband was being tortured in Gulf country by making him work relentlessly. The eight month old baby was at his feet, this child catches hold of Bhagwan's Thumb which was always constantly moving taking Rama name. The other hand was stroking the baby with utmost tenderness and Love.At the end of 30 mins Bhagwan says" Now you can take your child. My Father's work is done". He blessed her saying, "My Father will help you,you need not worry". The lady's husband comes back from.Gulf gets job elsewhere. They were happy. Ma Devaki says that child for 3 years of age would say " Anusha wants this, the Body wants this, it  wants something " always in third person. It was after 3rd year that parents got angry with her on that and changed this habit. Ma Devaki says 30min with Bhagwan and for 3 years the child was unable to say "I" and "Mine". 
 
Please follow the [link](https://youtu.be/aiXoMfd3QqY?si=HUy-8anuk3vc1PNU) for the satsang in youtube.
