---
title: 23 - Meeting of two smugglars with Bhagwan
author: Two smugglers 
date: "04/01/2020"
categories: [Sannidhi street]
---
Once two people had come to see Bhagwan. Bhagwan let them in and even made them sit. He then cast a penetrating look at them and asked what they were doing. One said he was selling handicrafts and the other said he was selling chappals. Then after a minute he asked again 'what are you doing'. Again one answered that he was selling handicrafts and the other said he was selling chappels. This went on eight times. People began to think Bhagwan had become senile. Then Bhagwan called all those people inside and made them put the same question to those two people. Now this also went on some eight times. By this time the two people realised that Swamy is not going to leave them unless they told the truth. They confessed that they were smugglers and weresmuggling sandalwood. They asked for forgiveness. Bhagwan said to them that it was not about being forgiven, they should not be doing such a bad thing, a papa. They said they would stop it and began to leave. But Swamy called them back and asked 'where are you going'. They said they were going to their village. Bhagwan repeated 'where are you going'. Now they knew that nothong can escape Bhagwan and told him that they were going to Salem to meeta certain person in this connection. Then Bhagwan sternly warned them that they would definitely be caught by the police if they went to Salem. The anger and the forceful words did something to them and this time they said that would really change their ways and take care of their families with hard earned money.  
 
Please follow the [link](https://youtu.be/-3nRBGjzYro?si=nqHBSsayFj6U-wjO) for the satsang in youtube.
