---
title: "Miraculous medical cure of Isswarya Kumaravel knee cancer."
author: "Mataji Devaki Ma"
date: "2021-06-06"
categories: [Leelas, Medical cure]
---

In 1995, they had a huge problem.Isswarya Kumaravel had conceived her second child. While Kumaravel was reversing his bike, Isswarya got hurt in her knee. They tried home remedies for three months but the pain did not go away. At the end of December, they took an xray, they were surprised. She had cancerous growth in her bone marrow and it had spread as well. He called his mother Thilagavathy Rajasekar and informed her. Isswaryaa's mother took her to a specialist in Chennai and he advised knee replacement surgery. He advised to abort the child to prevent complications arising out of surgery to the child. Isswarya was stubborn to carry the child. Uma , Thilagavathy Rajasekar asked them to inform Swami and they informed Bhagavan through Mani. Bhagavan was rubbing his right knee for sometime and while he got up after darshan, he fell down. Dr. Rajasekar came for the darshan of Bhagavan and Rajeswari Amma told him that there might be no darshan for three more days as he got hurt. However Karunaamoorthy Bhagavan came to the breakfast hut the following day. They had darshan of Bhagavan and He said, Thilagavathy is a friend of Lord Sundareshwara. Lord Sundareshwara will definitely help her. Definitely there is no need of operation for Isswarya.' This was informed to Isswarya and the doctor put plaster cast and sent her to Sivakasi. One day Isswarya fell down and hurt herself. Whatever we say will start becoming true. If you do japa for 8 hours, you will know that you are no different from the mantra and you will become the mantra. After that everything will be bliss. There will be no hunger, no sleep, no identification of others. You will be beyodn the mind and you will go closer to God. As you do japa intnesely, it will start pulling you towards God and take you to God. You will be beyond your control and you will surrender to God. You will get whatever you ask for. You knwo what is bigger happiness - God will start giving you everything that you need. Your word will become God's word.Your action will become God's action. The person asked what would happen after 8 hours of japa bravely. You will want to do japa all the time, all the 24 hours. You should do japa like your breath. it should be natural like your breath. 





