---
title: 21 - Muslim gets called from the long queue and Bhagwan blesses him
author: Muslim devotee Abdul 
date: "04/01/2020"
categories: [Sannidhi street]
---
Once a Muslim came to Ashram after Bhagwan's samadhi and prostrated before Bhagwan like a Hindu. He then narrated his story. Years back he was young, married with children. He was sufferring in abject poverty, sometimes with nothing to eat. Its because he got no job however much he tried. One day wallowing in self pity and agony as he was going, he met a Hindu friend of his who asked him why he was so miserable. On hearing his situation the Hindu friend asked him to go and see one Swamiji, our Bhagwan. The muslim, his name is Abdul said that he had heard about him but was apprehensive because VIPs came to see that Swamiji and he was muslim and very poor also. He had doubts if the Swamiji would see him. His Hindu friend said that he cannot have such thoughts even without making an attempt to see Bhagwan. So the next day Abdul went to see Bhagwan. The queue was very long, the sun was scorching and as time passed Abdul thought that he could never make it. He then even decided to leave. At that moment Bhagwan's assistant came running and shouting that there was a muslim in the queue whom Bhagwan wanted to see immediately. Abdul was surprised how Bhagwan knew he was a muslim. When he saw Bhagwan he prostrated but Bhagwan stopped him saying his religion did not permit that. Bhagwan then asked him what he wanted, blessed him and said "Sowkhiyama iruppe" meaning you will live well. Before leaving Abdul requested a photo of Bhagwan. To this Bhagwan said that in his religion they dont pray this way. Bhagwan blessed him saying "Pray to Allah. Allah blesses you". Thereafter in a few days he got a good job with a decent salary in the PWD department. He was posted elsewhere and he moved on. He was so happy and grateful to Bhagwan, he came to see bhagwan once or twice. After Bhagwan's samadhi he had come now and by this time it was 5'O Clock which was his Namaz time. He then sought permission to do Namaz in front of the samadhi siva linga of Bhagwan who was God himself. Everyone present were so moved by this, Bhagwan's compassion transcending all religions and all sects of people. 
 
Please follow the [link](https://youtu.be/IXu0X6W-VgY?si=89RpSj-LfHBwUN2X) for the satsang in youtube.
