---
title: 17 - Skylab will not fall on Chennai 
author: Thirumalai from Kovilpatti
date: "04/01/2020"
categories: [Conversations, Sannidhi street]
---
There was a prediction in 1979 by the scientists of the world that  America's Skylab would  fall on  Chennai, ie, on  12, July 1979. So may big authorities IAS and IPS officers were present before Bhagwan worried about this Skylab. A transister was giving a running commentary about its fall. Then Bhagwan made a statement that His Father was protecting India from Eternity to Eternity and that no harm will ever come to India or its people. He said that the Skylab will not fall on Chennai . It will fall into the ocean and chennai and its people will be protected. True to this within minutes announcements came in the transister that the Skylab had fallen not in chennai but in the ocean. All the great people sitting before Bhagwan were amazed. Thirumalai who was thinking that the scientists are telling one thing and this Bhagwan is saying something else immediately understood that Bhagwan was no ordinary beggar. Ma Devaki remembers the words of Bhagwan that He is the Cosmic Controller, He runs the Entire Cosmos. 
 
Please follow the [link](https://youtu.be/OtgnAfK6d_M?si=ZLL24CHosiKA3uko) for the satsang in youtube.
