---
title: 92 - Smt. Hilda meets Yogi in Sannidhi street house
author: Hilda
date: "07/01/2020"
categories: [Hilda Charlton/Will and Jones , Sannidhi street]
---
Hilda was exhausted after her journey but on receiving the lemons she felt better. She also narrates that when she approched the Sannidhi street house, she could see golden light everywhere even though it was at 11-11:30 at night. Ma Devaki narrates that Bhagwan welcomed her and 7 other people with her, Each was garlanded By Yogiji and gave her a mala that Bhagwan instructed she should keep with her always. Further narration of this experince where two children Named Mala and Valli who were with Hilda Ji, Valli was a clairvoyant who saw Golden aura around BHAGWAN extending from Horizon to Horizon. Bhagwan blesses Hilda ji and answers her questions, instructs her to continue her teaching. Ma Devaki emphasises on one question that Hilda asks Bhagwan that is "What is the relationship that a devotee should have with their ISHTA DEVTA ?" Bhagwan says "YOU HAVE TO SERVE THE LORD OF MANTRA, THAT YOU ARE CHANTING. ALONG WITH THE MANTRA YOU ARE CHANTING YOU MUST SERVE THE LORD OF MANTRA. THIS SHOULD BE THE KINSHIP, BEING A SERVANT OF THE LORD.  SERVE, SERVE SERVE UNQUESTIONINGLY. WHEN GURU GIVES SOME WORK TO DEVOTEE OR DISCIPLE HE GIVES GRACE TO DO IT, SO DEVOTEE SHOULD FEEL HAPPY IN DOING NOT THINK  IT AS A BURDEN " Hilda ji spent 4-5 days with Bhagwan during one of these Bhagwan became God Intoxicated and danced to Shri Rama Jai Rama Jai Jai Rama.
 
Please follow the [link](https://youtu.be/B_P1K7Ljaus?si=ID5Fnfcv5laL1ceM) for the satsang in youtube.
