---
title: 110 - Sri Rajan had a fight with his sister and Bhagwan through evolution in Biology taught him how to raise above his sisters actions
author: KankavelRajan
date: "07/01/2020"
categories: [Conversations, Sannidhi street]
---
Sri Kanagavelrajan was a zoology professor, who entered into baking business with his sister. Somehow they fall out and have a misunderstanding,  the sister declares that brother had never invested in the business despite him having put 10,000 rupees in the business. He ran to Bhagwan to lament about it, but Bhagwan even before he could say anything Bhagwan asks him if he knew about Theory of Evolution. Sri Rajan goes on to explain the same and in course is asked by Bhagwan to specifically ask what Theory of Mutation is. Sri Rajan elaborates by giving example of how butterflies in an industrial town became easy prey to enemies as they were colourful against soot that was being produced by heavy industrial work in the town. Over time their numbers declined and in defence their colour also changed to dark to escape being preyed upon. Sri Rajan says this is mutation fundamental change at gene level to protect oneself. Bhagwan then says This Beggar would like some mutation in you, And straight away asks him how much money had he put in the business. Sri Rajan was stunned as he had not even touched upon this story and Bhagwan already knew what was happening. Bhagwan guides him to leave the matter, go above his sister actions and rise above the selfishness. Sri Rajan slowly understands that Bhagwan was asking a fundamental change in him to go above the petty quarrels, be less selfish and maybe that would bring a change in his sister also. Bhagwan taught him to see through eyes of Love. 
 
Please follow the [link](https://youtu.be/gqzaBjdnUfk?si=fXgx0qPKxKvhoDEd) for the satsang in youtube.
