---
title: 81 - Srinivasan's frequent visits to Thruvannamalai 
author: Villivakkam Srinivasan
date: "06/01/2020"
categories: [Sannidhi street]
---
Srinivasan from Chennai was preparing to leave for Tiruvannamalai. His wife got angry and they had a quarrel. Srinivasan earlier had unwanted habits and after seeking Bhagwan blessings he came out of all those habits. His wife, while he was leaving asked him you were earlier spending money on those unwanted habits and now-a-days you spend on your frequent trips to Tiruvannamalai , because of which there is not much for household. Srinivasan then showed the photo of Bhagwan and told her to ask Him and left for Tiruvannamalai. On reaching Sannadhi street he waited outside Bhagwan house. Yogi came out and told him you had recently come why again and told him to go to Arunachala Temple and come. He finished having darshan at temple and came back and sat. There were devotees coming and going and 1 devotee after permission lighted agarbathi and camphor and showed to Bhagwan, whilst Srinivasan was wondering about God. After some time Bhagwan went in and brought a book and asked a devotee, Sridhar, to read from any page. When he read it came out that one must have faith in God. After all this Srinivasan got up and was leaving. Bhagwan called him and said you don't have to come frequently. When he reached home he narrated this to his wife, who said she had written in a chit and asked Bhagwan asking that her husband should not to go to Tiruvannamalai so frequently. 
 
Please follow the [link](https://youtu.be/noGoQ4uwE24?si=Ionm-u1JNdFX7AUH) for the satsang in youtube.
