---
title: 128 - Story of Gangappa was narrated by Bhagwan who was the collector of North Arcot . How he performed the Kumbabhishekam of Tanjavur temple
author: Gangappa
date: "01/02/2020"
categories: [Conversations]
---
Story of Gangappa was narrated by Bhagwan who was the collector of North Arcot and previously of Tanjavur...He came from a small village in Tumkur, Karnataka.
During his time, he worked hard and performed the Kumbabhishekam of Tanjavur temple which was tried by others but not fruitful (which earlier was done once in 1010 by Raja Raja Chola and then only perhaps in 1805.) 
Bhagwan said this was Father's wish that Gangappa had to come from Tumkur and work for the Kumbabhishekam, which was therefore a very divine incident.
Bhagwan said it was Father who carried out all actions through all people and that we are all mere puppets in His Hands. In fact, He said we did not do anything and we did not exist. In this great world stage, it is Father who is playing all these different roles through all of us.
 
Please follow the [link](https://youtu.be/BwWxdXcxlBU?si=KGgVhfIVlIc2xqGH) for the satsang in youtube.
