---
title: 26 - The naxalite says to Bhagwan there will be a 3rd world war. He saw Bhagwan grew bigger in size and saw planets hanging in the sky like fruits from a tree and Bhagwan said- THere will be no 3rd world war
author: Naxalite in Thiruvannamalai
date: "04/01/2020"
categories: [Conversations]
---
There was a naxalite who was hiding in the forests of Thiruvannamalai. Somehow he came into contact with Bhagwan. Bhagwan also had a knack of handling such fellows and he befriended Bhagwan. He used to give certain information and once told Bhagwan that China was moving things and a third World War was going to happen. Immediately Bhagwan began to walk fast. The nexalite ran after him keeping pace. Bhagwan climbed the steps of the Chariot Mandap, stood on the top step and began to grow physically in size. He grew bigger and bigger towards the sky and then this naxalite saw planets hanging in the sky like fruits from a tree. Bhagwan put out his hands, placed the planets here and there and extending his arms said that there will not be any Third World War. He gave such a blessing and then only returned to his normal stature. Bhagwan had averted the third world war and the nexalite who saw this Vishwaroopa Darshan was naturally flabbergasted and awe struck. He underwent a transformation and the friend became a devotee of Bhagwan. 
 
Please follow the [link](https://youtu.be/svAbjlIgg2g?si=wS7XXVKvkL7PWN7y) for the satsang in youtube.
