---
title: 22 - The moment they said 'Yes' Bhagwan flared up saying Jiddu Krishnamurthy was a great saint and elaborated on his great works
author: Sarala Panchapakesan
date: "04/01/2020"
categories: [sannidhi street]
---
Sarala Panchapakesan, her husband Panchapakesan an one Sri Ramachandran all journalists came from Hongkong to see Bhagwan. Bhagwan asked them how they came to know about this dirty beggar. They said they heard about Bhagwan from one Venkataramaniji who was a Nadi Jothidar. Bhagwan then spoke about various subjects and then as though he was testing them spoke very derogatorily about Jiddu Krishnamurthy. Sarala, Panchapakesan and Ramachandran all had high esteem for Sri Jiddu Krishnamurthy but when Bhagwan was talking like this, they did not know what to say and simply said 'Yes' agreeing with Bhagwan. The moment they said 'Yes' Bhagwan flared up saying Jiddu Krishnamurthy was a great saint and elaborated on his great works. He was saying that Jiddu Krishnamurthy might be easily misundertood by ignorant people. He then blessed them saying journalists must write highly about India, it's traditional wisdom and culture. 
 
Please follow the [link](https://youtu.be/67fZcOv0o34?si=duWsks5tLIYHZkrl) for the satsang in youtube.
