---
title: 29 - The crows caws are music to Bhagwan's ears. Bhagwan's reactions to Ilayaraja's music and crow's caws.
author: Janardhanan, Ilayaraja 
date: "04/01/2020"
categories: [Conversations]
---
Once Janardhanan while staying in Nadar lodge mansion, Bhagwan visited him. There were and a few other friends with them. Through the window they heard a crow crying out. It was such a terrible jarring noise. Anyone would have closed their ears but Bhagwan was listening to it as if it was excellent music. There is one other similar incident when Bhagwan, Ma Devaki and others were seated in a garden. Sri Ilayaraja had come to see Bhagwan. Bhagwan then asked him to sing. He sang so beautifully and after it was over all fell into a silence, a deep silence with Bhagwan's divine presence accentuating the pleasant evening making the atmosphere perfect. At that moment a crow began to cry and all were shaken out of the mood. But Bhagwan was enjoying this also saying it was his Father's sweet music and started laughing and laughing. These small-small anecdotes of Bhagwan show to his devotees the divine state he was in.  
 
Please follow the [link](https://youtu.be/k3Pa_X6nrm8?si=JBDicNlIaVGkNudA) for the satsang in youtube.
