---
title: 17 - Upma served to many people, Bhagwan had spoilt sambar, gave cashews to the devotee and ate the chillies. Gave very limited flowers to lots of devotees.
author: Srividhya 
date: "04/01/2020"
categories: [Devotees giving food to Bhagwan, Sannidhi street]
---
Srividhya, a devotee took Upma food for Bhagwan. Bhagwan used to accept food from her. This time when she went there were about 12 to 13 people in all. So she waited for them to leave to serve upma later. But Bhagwan asked her to serve to all. She had taken upma just enough for two people, but then she began to serve. Now like from an Akshaya Pathram, just as Krishna in Mahabharata took a grain of food and satisfied the hunger of Rishi Durvasa and all his ten thousand disciples, under Bhagwan's grace physical quantity of Upma grew  and all of them were satisfied. Bhagwan too had upma in his coconut shell. Another time one other devotee brought food and when Bhagwan asked her to serve, the sambar had been spoilt and was emanating a bad smell. Still Bhagwan ate and asked her what else she had brought. She had brought payasam and served that too in the same coconut shell. Now there were about a dozen cashews floating in it. Sri Vidya was happy that Bhagwan would have this. But then Bhagwan gave Srividhya, not even the other devotee who had brought them,  all the cashews one by one. Then Bhagwan asked the other devotee to serve sambar again. Now there were about a dozen chillies floating in it. Sri Vidya was afraid Bhagwan would make her eat them. She was asked not to take chillies and had avoided it in her diet. But to her horror Bhagwan took the chillies and ate all of them himself. He then smiled at her as if all her troubles had been taken by him and only good things given to her.  Once Bhagwan had a string of flowers some 7 or eight flowers in it. There were about 20 or so devotees and Bhagwan gave them flower prasad and as he kept giving somehow the quantity of flowers kept increasing and all of them received it. Still Bhagwan had a flower or two in his hands. He was Akshaya pathram himself.
 
Please follow the [link](https://youtu.be/OtgnAfK6d_M?si=ZLL24CHosiKA3uko) for the satsang in youtube.
