---
title: 92 - Will bumped into Bhagwan and He got angry and said -  When you are with this Beggar you must be very attentive, pay full attention to him
author: Mr Will
date: "07/01/2020"
categories: [Conversations]
---
Several times on long walks with Bhagwan it was seen Bhagwan would be carrying peacock feathers like a King's Spectre infront of him, Bhagwan would walk fast and would suddenly say stop. A car or a truck would be coming their way almost as if to run over them and the spectre of Peacock feathers would prevent that from happening.  Once in daytime on one of these walks Bhagwan stopped suddenly, Mr Will was admiring the Mountain and scenry and bumped into Bhagwan. Bhagwan got angry and shouted at Mr Will saying that When you are with this Beggar you must be very attentive, pay full attention to him, do not think of God, sadhana, beauty or mountain, this or that. Your whole attention should be on This Beggar" Ma Devaki says this is a lesson for all of us that  our whole attention should be on HIm alone and doing his SEVA. 
 
Please follow the [link](https://youtu.be/B_P1K7Ljaus?si=ID5Fnfcv5laL1ceM) for the satsang in youtube.
