---
title: 39 - Yogi Ramsuratkumar's involvement in building of memorial for Rajadurai nadar
author: Rajamanickam Nadar, Chandraprakash
date: "05/01/2020"
categories: []
---
It is said in the upanishad, when u know THAT - the ultimate truth, you know about everything else also. This incident shows how yogiji knew about so manythings even though He calls himself a dirty beggar.
Rajmanika Nadar &Rajdurai Nadar were a great devotee of Bhagwan insisted on purchasing a house at Sannathi street for Bhagwan ..Yogiji had suffered a lot at the hands of hooligans …to which he agreed.

In course of time, Rajdurai Nadar passed away. Rajamanickam Nadar wanted to a memorial for him and insisted that his son Chandraprakash to take permission from Bhagwan to have his memorial which was permitted by bhagwan. They visited Gandhigram and saw a gandhi stupi which was 32 feet. They reported this to Bhagwan and He okayed for 32 feet memorial. He visited place near Kanyakumari, Mailadi, bought a sample of polished granite and showed it to Bhagwan. Bhagwan had one look at it and said "NO".  THen he went to Mahabalipuram and showed the stone to Bhagwan but every time he said no. Bhagavan said near sivakasi, there is a place called "Kaiyanallur" . There is a mahatma called Ponaiyya swamigal. They had built a memorial . HE asked them to go and ask where they got the stone. They found it was from Kodangipatti. They saw 5 hills and there was a village with stone cutters doing their job for generations.  Then Bhagwan aksed him to go to mahabalipuram and meet Ganapathi stapathi to get the drawing ready. Ganapathi stapathi was an expert in temple architecture. He happily agreed to do the job after he heard the name of Bhagwan and insisted to meet Bhagwan. Then Bhagwan approved the drawing. He wanted 16ftx16ft stones.  The people in Kodangipatti said, out of the 5 hills, they use only 2. One had a murugan temple and the other two  the stones were brittle. So they said 16x16ft stone is not possible . 
Bhagwan asked Chandraprakash to describe what he saw there in Kodangipatti. Swami said go ask the stone cutters to cut stone from the mountain that is facing the Murugan temple. The stone cutters said that the hill that swami had mentioned is very brittle. But Swami insisted.. only that mountain should be cut. So he approached the people again and insisted to cut that hill. Then they agreed but wanted daily wages. They used an explosive and to their surprise, they found out that it was not brittle. They could find huge stones as requested by Ganapathi sthapathi. 
Swami also asked Ganapathi stapathi to go see Gyananandha memorial..It was hexogonal and Swami said he wanted the same kind of structure. When it was completed, Bhagwan said it will be a holy place and it will be this Beggar's statue there. And who ever came and prayed there after lighting agarbathi, their prayers will be answered.
 
Please follow the [link](https://youtu.be/mFzeaVIBBKk?si=-gI5AEw3bN-c-tvI) for the satsang in youtube.
